<a href="https://colab.research.google.com/github/athens-21/DE242/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [3]:
import numpy as np

In [4]:
lst = [(1,2,3,4), (6,7,8,9)]
arr = np.array(lst)
print(arr)

[[1 2 3 4]
 [6 7 8 9]]


**zero(shape)** function —Create a NumPy array with values
initialized to zeros

In [5]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


**ones(shape)** function —Create a NumPy array with values
initialized to ones

In [6]:
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


**eye(shape)** function —Create an identity NumPy array with values
initialized to ones along the diagonal.

In [7]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### **Converting an Ndarray to 1D Array**

**ravel()** returns a view of the **original** array —changing values in
the output array WILL change those in the original array

In [8]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

**flatten()**  —returns a **copy** of the original array —changing values in
the output array will NOT affect those in the original array.

In [10]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Creating a two-dimensional array**

In [12]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
print(arr.ndim)

2


In [14]:
#using ravel()
rav1 = arr.ravel()
print(rav1)

[1 2 3 4 5 6 7 8]


In [15]:
rav1[0] = 100
print(rav1)

[100   2   3   4   5   6   7   8]


In [16]:
#using flatten()
fl1 = arr.flatten()
print(fl1)

[100   2   3   4   5   6   7   8]


In [17]:
fl1 = arr.flatten()
fl1[0] = 1
print(fl1)

[1 2 3 4 5 6 7 8]


**Two Ndarrays Vertically**

In [18]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 = np.array([[9,10,11,12], [13,14,15,16]])

In [19]:
#np.concatennate
arr3 = np.concatenate((arr1, arr2), axis = 0)
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [20]:
#np.vstack
arr4 = np.vstack((arr1, arr2))
print(arr4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


**Two Ndarrays Horizontally**

In [21]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 = np.array([[9,10,11,12], [13,14,15,16]])

In [22]:
#Horizontal concatenation  ➡️, ⬇️
np.concatenate((arr1, arr2), axis = 1)

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [23]:
#hstack
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

**Reshaping a numpy array**

In [24]:
#An array example 3
arr = np.arange(1, 9, 1)
print(arr)

[1 2 3 4 5 6 7 8]


In [25]:
print(arr.ndim)

1


In [26]:
print(arr.shape)

(8,)


In [27]:
#Reshape the array to (2,4)
arr = arr.reshape(2,4)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [28]:
print(arr.ndim)

2


In [29]:
print(arr.shape)

(2, 4)


In [30]:
arr[0,0] = 99
print(arr)

[[99  2  3  4]
 [ 5  6  7  8]]


In [31]:
tmp = arr.reshape(4,-1)
print(tmp)

[[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


In [32]:
print(tmp.shape)

(4, 2)


In [34]:
#using slice indexing arr[start:stop:step]
print(tmp[1,0:2])

[3 4]


In [35]:
print(tmp[1,0:2:2])

[3]


**Find Data in Numpy Array**

In [36]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
np.where(arr<3)


(array([0, 0]), array([0, 1]))

In [37]:
arr[np.where(arr>3)]

array([4, 5, 6, 7, 8])

In [39]:
#Gives an explicit bool array
result = np.where([True, False, False], [1,2,3], [7,8,9])
print(result)

[1 8 9]
