<a href="https://colab.research.google.com/github/athens-21/DE242/blob/main/NumpyPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [ ]:
import numpy as np

In [ ]:
lst = [(1,2,3,4), (6,7,8,9)]
arr = np.array(lst)
print(arr)

[[1 2 3 4]
 [6 7 8 9]]


**zero(shape)** function —Create a NumPy array with values
initialized to zeros

In [ ]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


**ones(shape)** function —Create a NumPy array with values
initialized to ones

In [ ]:
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


**eye(shape)** function —Create an identity NumPy array with values
initialized to ones along the diagonal.

In [ ]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### **Converting an Ndarray to 1D Array**

**ravel()** returns a view of the **original** array —changing values in
the output array WILL change those in the original array

In [ ]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

**flatten()**  —returns a **copy** of the original array —changing values in
the output array will NOT affect those in the original array.

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Creating a two-dimensional array**